### PR TITLE
Add developers

### PR DESCRIPTION
**Pull request by keilw**
Without <developers> present MavenCentral will block any contribution. So I added the two project leads @jclingan and @kwsutter (hoping we won't have any tedious discussions about others to mention here?;-)

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Are you sure?

WildFly Swarm has artifacts pushed to Maven Central without a `<developers>` section

**Comment by struberg** [comment]
-1

- Agree with @kenfinnigan that the developers section is not needed by maven.central.
- Also please don't add random authors, copyright and developers to projects where those people didn't commit a single line. That's not how intellectual property rights work!
- 9 commits for adding 2 developer tags? serious?

**Comment by keilw** [comment]
Sorry it is. Maybe Sonatype changed it recently but https://repo1.maven.org/maven2/org/w3c/ddr/ddr-simple-api/20081205/ddr-simple-api-20081205.pom was not allowed there until the contributors to the W3C DDR spec were added first. It was simply refused by Sonatype without it. See plenty of recent articles like http://stackoverflow.com/questions/40423087/error-in-publishing-artifact-to-maven-central

But @struberg good luck trying it without that.
Btw. there are just 2 commits, the others are already in there ;-)

**Comment by keilw** [comment]
You could even add 'Donald Duck' here, Sonatype won't care, but I thought the project leads would be best to reflect that at the top level.

Write what you think or fail trying to leave them out...

**Comment by keilw** [comment]
@kenfinnigan When was that last done without developers???
http://central.sonatype.org/pages/requirements.html
Is rather clear. And as mentioned I had to add everything to the POM you see in https://repo1.maven.org/maven2/org/w3c/ddr/ddr-simple-api/20081205/ddr-simple-api-20081205.pom before Sonatype accepted it. In my experience at least after early this year `A Complete Example POM` is the minimum requirement for every artifact now, not just those with a JAR, but please get a Sonatype JIRA user or ask @dblevins to do it as promised and see how far you get.

**Comment by kenfinnigan** [comment]
@keilw at least once a month for the last 7 months.

Your tone and attitude are not appropriate. I was simply asking whether you were sure that section was required because in my own experience it hasn't always been.

**Comment by keilw** [comment]
@kenfinnigan when was this artifact first added? I am sure they may not check it for existing artifacts but it looks like you must have it if one gets newly introduced. I've been doing that a lot (adding new ones) in recent months and weeks so I think I have the experience to tell if they'll accept it or not. The attitude is better than constant "No please OMG no developers" folks who keep blocking this and other artifacts for weeks or even months now ;-/  I lasts tried it less than 7 weeks ago and many of the Stackoverflow reports are as new as Nov or Dec 2016 so it is safe to assume Sonatype tightened up its IP checks, too.

**Comment by keilw** [comment]
And if you have more Bintray users, let us know both @otaviojava and I are there https://bintray.com/microprofile as we did for JNOSQL.

**Comment by keilw** [comment]
Sounds like a case of Too Many Cooks so far. At least 3 Sonatype users all of whom are also committers had contribution rights to MavenCentral for 3 weeks now, but did not use it ;-/
Nor has the simple but rather important step of tagging happened. That leaves 1.0 Without a Trace so far. Would be good if someone tagged it now (assuming it is valid for Sonatype, but a tag could always be relabeled and I believe everyone with push rights could also reopen and/or merge a PR if found appropriate)

GitHub even says
>Releases are powered by tagging specific points of history in a repository. They’re great for marking release points like v1.0.

**Comment by kenfinnigan** [comment]
Artifacts were probably added a year or so ago, they've had many name changes!

We've been continually adding new artifacts to Central over past months without issue

**Comment by keilw** [comment]
Frankly I have no idea what kind of API you may use or why it behaves differently because this issue (most have a JIRA user there now, should it be necessary to log in) from 2014 regarding a **Parent POM** shows it was necessary at least 3 years ago: https://issues.sonatype.org/browse/OSSRH-12676

The ticket was filed by Itemis btw, a long term Eclipse committer and lead of several projects, so why not ask them, too.

**Comment by keilw** [comment]
There must be a major inconsistency and mess in how things to into MavenCentral I'm afraid ;-|
Whatever channels or APIs you called, it seems KumuluzEE who just joined the project/initiative also used them, and managed to bypass developer tags in every POM I spotted here https://search.maven.org/#search|ga|1|kumuluz 
I know at least the Bintray update bridge to sync with MavenCentral will not allow it, and https://github.com/andrearn/org.fornax.soa.xtextservicerepository pointing to a Bintray hosted P2 repo suggests, https://issues.sonatype.org/browse/OSSRH-12676 was probably caused there, too. So please use the MavenCentral > JCenter route by whatever means possible. Or let's add developers.

Java EE has always done, the first EE 5 POM https://search.maven.org/remotecontent?filepath=javaee/javaee-api/5/javaee-api-5.pom contains the Spec lead or "project-owner" so almost every JSR is obliged to state at least one Spec Lead in this place. That's why I proposed to do the same with @kenfinnigan and @jclingan 
If nobodoy wants to follow what all the underlying standards also do for the past 7+ years, then so be it, but it restricts how artifacts can be deployed.

**Pull request closed without merging**
